name: CI/CD

on:
  push:
    branches:
      - 'master'

jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: Ubuntu-20.04
    defaults:
      run:
        working-directory: ./infra/terraform/aws/application/demorestapi/lambda
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - uses: papeloto/action-zip@v1
        with:
          files: demorestapi.py
          dest: demorestapi.zip
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: demorestapi
          zip_file: demorestapi.zip
          handler: demorestapi.lambda_handler
          role: ${{ secrets.AWS_LAMBDA_EXECUTION_ROLE }}
          runtime: python3.8